#!/bin/bash

if [ -z $1 ]; then
    echo "Need a filename"
    exit 0
fi

cat <<EOF >> $1.ovpn
#############################################
#     _                                     # 
#    /  _ ._ ._  _ ._|_|o _ |_      _.      # 
#    \_(_)|_)|_)(/_| | ||(_|| |\/\/(_|\/    # 
#         |  |            _|          /     # 
#############################################

# if you edit this file, you may fuck it up.
# so, don't edit the file unless you know
# what you're doing, k?

#********************************************
# THIS FILE WAS AUTOMATICALLY GENERATED BY  # 
#             make_unified.sh               #
#********************************************

client
dev tun
proto udp
remote copperhighway.org 1194
resolv-retry infinite
nobind
user nobody
group nobody
persist-key
persist-tun
comp-lzo
verb 3

<ca>
EOF
cat /home/git/Projects/easy-rsa/easyrsa3/pki/ca.crt >> $1.ovpn
cat <<EOF >> $1.ovpn
</ca>
<cert>
EOF
cat /home/git/Projects/easy-rsa/easyrsa3/pki/issued/$1.crt >> $1.ovpn
cat <<EOF >> $1.ovpn
</cert>
<key>
EOF
cat /home/git/Projects/easy-rsa/easyrsa3/pki/private/$1.key >> $1.ovpn
cat <<EOF >> $1.ovpn
</key>
EOF



