#!/bin/bash

if [ -z $1 ]; then
    echo "Need a filename"
    exit 0
fi

cat <<EOF >> $1.ovpn 2> errors.log
#############################################
#     _                                     # 
#    /  _ ._ ._  _ ._|_|o _ |_      _.      # 
#    \_(_)|_)|_)(/_| | ||(_|| |\/\/(_|\/    # 
#         |  |            _|          /     # 
#############################################

# if you edit this file, you may fuck it up.
# so, don't edit the file unless you know
# what you're doing, k?

#********************************************
# THIS FILE WAS AUTOMATICALLY GENERATED BY  # 
#             make_unified.sh               #
#********************************************

client
dev tun
proto udp
remote copperhighway.org 1194
resolv-retry infinite
nobind
persist-key
persist-tun
comp-lzo
verb 3
user nobody
group nobody
cipher AES-128-CBC
remote-cert-tls server

<ca>
EOF
cat /etc/openvpn/server_pki/ca.crt >> $1.ovpn 2> errors.log
cat <<EOF >> $1.ovpn 2> errors.log
</ca>
<cert>
EOF
cat /etc/openvpn/easy-rsa/easyrsa3/pki/issued/$1.crt >> $1.ovpn 2> errors.log
cat <<EOF >> $1.ovpn 2> errors.log
</cert>
<key>
EOF
cat /etc/openvpn/easy-rsa/easyrsa3/pki/private/$1.key >> $1.ovpn 2> errors.log
cat <<EOF >> $1.ovpn 2> errors.log
</key>
key-direction 1
<tls-auth>
EOF
cat /etc/openvpn/server_pki/ta.key >> $1.ovpn 2> errors.log
cat <<EOF >> $1.ovpn 2> errors.log
</tls-auth>
EOF
